### ISSUE TITLE
Huge log files

### ISSUE THREAD

**Issue by bornakke** [medialab/hyphe#132]
Hi Medialab,

We just discovered that our hyphe instance had created around 15 gb of log files after being used for 2 months. The files are located in subfolders in /var/log/scrapyd/

Can these files be deleted without any risk? And is their any way to make hyphe store less log files from its processes?

Best
Tobias

**Comment by boogheta** [comment]
Hey Tobias,
This is not due to Hyphe, only Scrapyd, which indeed dumps a lot of log which are not really useful, one of the many reasons we need to get rid of it on the long term.
You can safely clean these, no worries. Ideally just stop scrapyd before you remove the log files in the directory then restart it (and if you do sop check before you stop it that no crawljob is currently running)
