### ISSUE TITLE
Export full text?

### ISSUE THREAD

**Issue by joelgombin** [medialab/hyphe#150]
Hi,

I know we discussed that already a few months ago, but with the new release, I was wondering if there's a way to export all text from a web entity's pages? I can think of a lot of applications for that. Also I've seen there's an API so it opens a lot of nice possibilies for external modules...

**Comment by boogheta** [comment]
Hey, yes there are options but there are still experimental for the moment.

The best option so far is our repo (Hyphe2Solr)[https://github.com/medialab/hyphe2solr/] which indexes the whole text of the crawled pages per webentity in a Solr engine so that it can be requested.

Although this option will leave you with a new index database but not some kind of csv or other file containing the whole text per webentity as you might want. 

In which case, I'd recommand you to adapt the code from hyphe2solr since it does everything you want, just remove the solr parts. So basically edit the file `index_hyphe_web_pages.py` as such :
- replace the solr connection block [l.204-213](https://github.com/medialab/hyphe2solr/blob/master/index_hyphe_web_pages.py#L204-L213) with something such as solr=None
- replace line 94 with whatever you want to store the data in, like mongo save, write a textfile, etc 
- comment line 289

**Comment by Jollivet** [comment]
Hello,
I had Hyphe installed on a server on my university (UTC).
But I discovered then that there was no way from the interface to access the text contents of crawled pages and webentity (unlike I had understood). 
Did you manage, joelgombin or boogheta,  to implement the suggested modification on the former post ? 
That would be great ...
If not, too bad, I'll have to drop Hyphe for a while ..
Pascal

**Comment by boogheta** [comment]
Hi @Jollivet 
As explained, Hyphe rcords the full text content of each crawled webentity but does not provide access to this content from the frontend yet.
If you know a little bit how to program, you can easily access and process these content directly from the mongodb database where it is stored. The scripts and lines given above can help you do so.
Otherwiser no sorry, you'll have to wait until we get the time to develop these features (but it won't be before a while)

**Comment by JoshuaJoma** [comment]
Hi boogheta,

thanks again for your work on this helpful software. It gave me good insight already and I enjoy learning about the structure of the web! 

The next step for me would be to do some text analysis with the content of the crawled pages. I therefor try to figure out how to extract the content of the stored webpages like Jollivet did several years ago. 

I tried the SolR script but couldn't get it working. 

That's why I used a viewer for the mongodb (Robo 3T) to understand the structure of the database. I can see all the databases for the corpses I created there but can't find the content of the webpages anywhere. 

Do I have a mistake in thinking? Can you point me to the right place where I can find the content of the pages?

Then it would be easier to write a script to extract the content in a way I need it. 

Thanks a lot!

Best,
Uwe

**Comment by boogheta** [comment]
Hi @JoshuaJoma, a couple things to answer your question:
- first, text contents are collected only if the option "store_crawled_html" is set to True to do so in the config
- then, they are stored in the "body" field of the pages stored in the `HYPHE_MONGO_DB_NAME/CORPUS_ID.pages` collection of the mongo, BUT they are stored binary data zipped from the actual html text content to lighten it a bit.
So first, you should check there are actual contents stored for your corpus and restart it with the option set to true otherwise.
Then only maybe retry hyphe2solr (although the codebase is a bit old and may need a few changes to adapt to Hyphe's latest developments)
