### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by bornakke** [medialab/hyphe#163]
Hi Medialab,

Our last instance of hyphe had been installed wrongly. We therefore setup a new instance yesterday. To our happy suprise all old data were migrated with it and everything seems to work.

Only problem is that we hadn't noticed that hyphe are now using a salt for its password and the old salt file weren't moved along. We can access our old stuff through the admin interface, but we will rather not share this admin access to everyone who had data on the old instance.

Is it possible for an admin to reset a corpus-password? If not, is there then any way to export all webentities from the old corpus and over into a new. I have tried to use the export function which works fine, but I can't seem to get the webentities in again.

Best
Tobias

**Comment by boogheta** [comment]
Hi @bornakke, since they're encrypted with the salt, I'm afraid you can hardly change the passwords unfortunately.
I see two options : 
- one would be for each corpus to forge by hand the hash of a new password in python using the salt and the crypting function from hyphe-backend/lib/utils.py then modiffying the saved hash for the respective corpus in the "corpus" collection of the mongo database
- the other, simplier but less safe (it depends whether keeping protection for these old corpus is critical), would be to simply make all your old corpora not password-protected by simply setting to an empty string ("") the password fields of all entries in the corpus collection of the mongo database
I'm off for ten days of holidays starting tomorrow, I can briefly help maybe this afternoon online on IRC if you need, otherwise, that will have to wait until march 6th

**Comment by boogheta** [comment]
BTW, regarding your fallback question, reimporting a corpus is currently not the easiest thing to do. Basically exports only give details on the webentities, the crawls and their links, but the content data is lost and you need to basically rebuild the corpus by redefining the entities and start over all the crawls.
Functions to do this will get in eventually, but for now, you need to write some scripts that requests the backend API and redefine everything accordingly, including start pages and depths of crawls.
You can read an example of such script there : https://github.com/medialab/hyphe/blob/master/bin/samples/start_crawling_webentities_from_csv/start_crawling_webentities_from_csv.py

**Comment by bornakke** [comment]
Hi Boogheta,

Thank you for your quick response. Unfortunately I have never worked in a mongo db. Removing password will be just fine, but I have no idea how to change the password field. How difficult is it?

Best
Tobias

**Comment by boogheta** [comment]
Something like this should do the trick, assuming hyphe is the name of the `db_name` defined in your `config.json`:
```bash
mongo hyphe
db.corpus.update({}, {$set: {password: ""}}, {multi: true})
```
This will set it for all the corpus, if you ant to restrict it for instance to a list of corpus ids, you can specify it like this:
```bash
db.corpus.update({"_id": {"$in": [id1, id2, id3]}}, {$set: {password: ""}}, {multi: true})
```

**Comment by bornakke** [comment]
Bingo! Worked like a charm :+1:

**Comment by bornakke** [comment]
Thank you!
