### ISSUE TITLE
New ubuntu versions?

### ISSUE THREAD

**Issue by bornakke** [medialab/hyphe#188]
Any chance that hyphe will support 16.04 or 15.10 in the near future? We have a new server we would like to experiment on, but other apps forces us to run newer versions of ubuntu.

**Comment by boogheta** [comment]
Hello Tobias,
It's part of my summer todo to finally release v0.3 that should support more recent distributions. Although my latest tryouts with 16.04 were not much concluding because of @scrapy's scrapyd not wroking with Ubuntu's new systemd service handling. Will let you know more when 0.3 is released.
Although, I haven't tried with 15.10 (and won't, we don't have enough manpower to maintain more than LTS versions) and I don't know whether it was already relying on systemd or still using upstart. In the latter case, it might just happen to work if you try the full install from git clone (not from release 0.2)

**Comment by bornakke** [comment]
Maybe this will work?
https://github.com/scrapy/scrapy/issues/2076

I will just await 0.3 - for once I'm not in a rush :)

**Comment by boogheta** [comment]
this is scapy, not scrapyd which is our culprit, but this lies under the same poor maintenance of distributions support on their side, yes. Will let you know when the rlz is out!

**Comment by boogheta** [comment]
Hey @bornakke, as announced earlier on, we finally released a new version with a more generic installation process which should allow you to easily install Hyphe now.
