### ISSUE TITLE
hyphe start fails after fresh install on ubuntu 14.04 server

### ISSUE THREAD

**Issue by JoshuaJoma** [medialab/hyphe#208]
Hi,

tried installing the cloned hyphe version via script and manualy (line by line) on a ubuntu 14.04 server in a virtualbox. 
I already went through the other issues but couldn't solve it. 

The installation via the install-script worked without problems but starting via 
./bin/hyphe start fails

See hyphe-core.log:

[hyphe-core.log.txt](https://github.com/medialab/hyphe/files/1078923/hyphe-core.log.txt)

When loading http://localhost/hyphe in a browser
it says: YOU ARE DISCONNECTED FROM HYPHE    :-( 

http://localhost:6800/listprojects.json
is shows {"status": "ok", "projects": ["hyphe.test", "hyphe.--test-corpus--"]} 

Help is appreciated. 

Best regards,
Uwe

**Comment by boogheta** [comment]
Hi I think your problem is due to too recent versions of txmongo/pymongo installed, cf #207 
You can try fixing it by forcing installation of specific version in your hyphe virtualenv and globally for scrapyd : 

```
sudo pip uninstall txmongo pymongo
sudo pip install pymongo==2.7 txmongo==0.6
workon hyphe
pip uninstall txmongo pymongo
pip install pymongo==2.7 txmongo==0.6
```

PS: We are in the process of rebuilding a lot of things (cf branch named traph) so we won't be maintaining installation of the actual master branch and will provide an easier install in the coming months, so I'm closing install related issues as of now, but feel free to continue reporting/asking questions in the thread.

**Comment by JoshuaJoma** [comment]
Hi boogheta,

thanks it worked.

Uwe

**Comment by boogheta** [comment]
Hi @JoshuaJoma , as announced earlier on, we finally released a new version with a more generic installation process which should allow you to easily install Hyphe now.
