### ISSUE TITLE
Focussing options for crawling with Hyphe

### ISSUE THREAD

**Issue by gollivier** [medialab/hyphe#256]
The work already done is huge! But, would it be possible to implement some parameters allowing Hyphe to become a focused crawler, ie to select only webentities related to some specific issues during the crawling?
 This could be simply by presence of a set of keywords in pages/sites (0/1 or with density) or with more elaborated approaches using supervised learning or others that can be found in literature (like in ACHE https://github.com/ViDA-NYU/ache or Domain Discovery Tool http://domain-discovery-tool.readthedocs.io/en/latest/)

**Comment by boogheta** [comment]
Hi @gollivier, focus crawling is a different approach than Hyphe's, which intend to avoid selecting automagically the entities to crawl and rather lets user take action and decide individually which website to include or not in the corpus. IssueCrawler or the other crawlers you pointed are more fitted for such use imho.
Also, filtering pages depending on the presence of a set of keywords within can considerably slow things down as it supposes to actually crawl everything and then only keep the desired ones, whereas Hyphe only crawls pages to be included.

**Comment by gollivier** [comment]
I see some possible complementarities between hyphe and focused crawling strategies. In term of speed, focused crawling allows to avoid the crawling of unrelevant sites or pages. This also could be a complementary help to build the corpus, ie to know what are "the pages to be included". In the actual situation this inclusion decision of a page/site is based upon a quite vaguely estimated relevance to the extent that, unlike Navicrawler, the immersion  in the webpage content is limited. Thus, my suggestion is not to automatically crawl the content of all discovered pages but to measure the relevance of the page/site that the user proposes to crawl in order to exclude it, automatically or not, if they are irrelevant according to the user criterion and thus avoid  identifying "useless" hyperlinks.  Again this is just a suggestion related to my concerns as a user of Navicrawler and Hyphe.

**Comment by boogheta** [comment]
What I was explaining is that to "measure the relevance of the page/site" you need to have some information which can hardly come from anything else than crawling it. Since crawls are already limited to the selected webentity, the only information you have to help take such decision without precrawling are the url and the text of the links towards it.

**Comment by boogheta** [comment]
What I was explaining is that to "measure the relevance of the page/site" you need to have some information which can hardly come from anything else than crawling it. Since crawls are already limited to the selected webentity, the only information you have to help take such decision without precrawling are the url and the text of the links towards it.
The whole purpose of Hyphe in opposition with most crawlers is to avoid automaticity and ensure the user decides what is crawled or not.
If you want to identify by word filtering on urls which entities to choose, this can already done using the search bar in the prospect page.

**Comment by boogheta** [comment]
I guess minet's hyphe and focus crawling methods will now allow us to do things like this (although still in CLI)

**Comment by boogheta** [comment]
@Yomguithereal I guess minet's hyphe and focus crawling methods will now allow us to do things like this (although still in CLI) ?
