### ISSUE TITLE
Crawl works but shows 0 page crawled

### ISSUE THREAD

**Issue by jacomyma** [medialab/hyphe#269]
Crawling this page as a web entity ( slider on the right ) on the demo and my dev instance on 2018-06-06 in an empty corpus:
https://www.google.com/search?source=hp&ei=ynUNW5HQKoTWU4C5j4gJ&q=climate+change&oq=climate+change&gs_l=psy-ab.3..0i131k1j0l9.944.2676.0.2869.14.14.0.0.0.0.56.539.13.13.0..2..0...1.1.64.psy-ab..1.13.537....0.TsLD8A1PwvQ

On the demo the crawl works, has 1 page crawled, 118 discovered pages and 117 links, and is marked as achieved.
On my dev instance though, it has 0 page crawled and is marked as unsuccesful. Yet it has 130 discovered pages and 130 links.

It looks like there might be a redirection that is handled differently. Anyway it is quite funny that there is some crawled content but supposedly 0 page crawled.

**Comment by jacomyma** [comment]
I just realized it's a different problem: all crawls are marked as 0 page crawled on my dev instance (though they are actually crawled).

**Comment by boogheta** [comment]
I don't see how to reproduce and it feels like this might be some border effect of some kind. Could you try and check whether this still happens on your local instance and otherwise close this.
BTW I think I fixed the issue with Docker installs on Windows, so you should be able to redeploy locally for this test, just setup in .env the TAG to "preprod", then docker-compose pull and docker-compose up (and i'm interested in your feedback whether it actually works again under windows or not! :) )
