### ISSUE TITLE
add default entity creation rules

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe#295]
on those prefixes:
https://www.instagram.com/
https://www.youtube.com/channel/
https://www.youtube.com/user/

**Comment by boogheta** [comment]
We deliberately did not set those as default rules because of the url stuctures of these websites: it would generate plenty parasite entities whereas these entities wouldn't actually reflect the videos or posts of the authors (youtube.com/watch?v=IDVIDEO & instagram.com/p/IDPHOTO/)

**Comment by paulgirard** [comment]
I see.
Can't we create default web entities for youtube or instagram services with respectively the /watch and the /p prefixes to avoid te creation rules to be triggered by video or picture ?

**Comment by boogheta** [comment]
I was not clear: for youtube the rule wouldn't trigger on "watch?v=" urls since the /user/ or /channel/ prefix wouldn't be present, for instagram we would need indeed to create a dedicated entity including both root and /p prefixes to avoid this.
But my point was different: I meant mostly that there is not real interest of having such "user" entities if they cannot reflect the user's productions. Links to these domains from elsewhere than the author itself are usually not to the user page but rather direct links to videos or posts, which are not attachable to their author through the url. So creating these rules would generate a lot more entities without them having much interest for the corpus definition I believe.

**Comment by paulgirard** [comment]
The limit of hypertextuality about platforms.
My personnal conclusion on this is : you're right this must not be a default creation rule.
And to be able to analyse communities effects through youtube or instagram via HTTP and not the APIs would mean create "media based" (video of picture) web entities as proxies. Which is possible but would create a very large amount of WEs.
