### ISSUE TITLE
Front end QoL : in prospect, allow opening a new tab to start crawling entity newly marked as IN

### ISSUE THREAD

**Issue by Guillaume-Levrier** [medialab/hyphe#334]
When your Hyphe is crawling/managing many WE, it takes ages to load the prospect tab, and a few more dozen seconds for the search function to find what you want. Being able to alt+click or right-click the [crawl] button would make Hyphe a lot smoother to use. Right now I have to wait 60-180 seconds between clicking the crawl button and getting back to my prospects because it wants to load the CRAWL tab in the same window, which I think doesn't make sense.

**Comment by boogheta** [comment]
This is not possible as the website is coded right now (entities to be crawled are retained in ram within the tab, not passed through the url) so that would be too much development i believe.
The problem you describe looks more like a reactivity problem to load the prospect entities, which should have been significally improved in more recent versions of Hyphe, are you using your own or the one we deployed for your project?

**Comment by Guillaume-Levrier** [comment]
The one you deployed for the project.

**Comment by boogheta** [comment]
This is weird, it shouldn't be so slow (and it isn't as I try it now, maybe there was a temporarily overload on our servers then?)
