### ISSUE TITLE
Speed up docker builds by not using Alpine?

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/hyphe#374]
Interesting opinion ;) https://pythonspeed.com/articles/alpine-docker-python/

**Comment by boogheta** [comment]
Indeed, cc @jri-sp ! :)

**Comment by boogheta** [comment]
Indeed, cc @jri-sp ! :)I think the main change it would help wioth is when installing lxml, which takes a very long time to build every time

**Comment by jri-sp** [comment]
I'm not agreed with all in the article, especially the final paragraph because if your dependencies are working well with musl then Alpine is still a good option. 
For the image size argument, they don't remove all the building stuff that they've installed... so yes the final image is bigger :)

Anyway, with Hyphe it could really worth it and I can make a new branch using `python:2.7-slim` if you want ? And then we can compare :)

**Comment by Yomguithereal** [comment]
Yeah \o/ FOSDEM style!

**Comment by boogheta** [comment]
sounds like a plan!

**Comment by jri-sp** [comment]
I've pushed https://github.com/medialab/hyphe/commit/8651204dd091ed68cff222faa3cec3a63de40c4e on a new branch [dockerfile-debian](https://github.com/medialab/hyphe/compare/dockerfile-debian).

Built it with my laptop  (`Intel core i7 2,9 GHz-4 physical cores, 8 logical ones / 16GB RAM / 512Go SSD`):

| backend   |      Time      |  Size |
|----------|:-------------:|------:|
| python:2.7-slim |  3:35,01  | 258MB |
| python:2.7-alpine |    5:48,36  |  206MB |


| crawler   |      Time      |  Size |
|----------|:-------------:|------:|
| python:2.7-slim |  2:24,73 | 251MB |
| python:2.7-alpine |    5:59,41  |  199MB |

(I've pulled `python:2.7-alpine`& `python:2.7-slim` before `time docker build ...` )

Note: total build time also depends on debian/alpine repos and cache when downloading packages.

But for the `lxml` building part, it's quicker. ;)

I've tested the stack with a little crawl and it works, but this requires further testing because it's a big change :)

So... Do your tests and if you think this stuff is worth it then merge it to master :)

**Comment by boogheta** [comment]
Seems like not a too big size increase for quite an acceleration, which sounds useful to me.
I'll try to run it and see if we want to merge!
